os:
  editPreset: "nvim"
gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
git:
  pagers:
    - colorArg: never
      pager: delta --dark --paging=never --line-numbers --features chameleon
customCommands:
  - key: "U"
    command: "git submodule update --init --recursive --force"
    context: "files"
    description: "Force update and reset all submodules"
    output: log
